swagger: "2.0"
info: {}
basePath: /api/v1
paths: {}
definitions:
  controllers.Response:
    title: Response
    type: object
    properties:
      data:
        $ref: '#/definitions/controllers.interface'
      message:
        type: string
      success:
        type: boolean
  controllers.interface:
    title: interface
    type: object
